### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/authy#4]
Hi @Omranic,

Nice work! I did a quick code review on this repo and made the following changes so this package works more or less the same as the others ones in our organization:

- added a static method`missingCredentials` in the `InvalidConfiguration` class
- the styleci preset has been set to `laravel`

In general think in general passing booleans to methods makes for less readable code. I've also changed the `force` method so that it doesn't take a bool anymore and added a dedicated method `doNotForce` that sets the `force` property to false. 

Because of that change I've also removed the current `1.0.0` tags and added `0.0.1`. Why? Because tagging something with a version less than `1.0.0` breaking changes are still allowed (and the `force` method change is breaking.  Feel free to tag it as `1.0.0` if you feel it's ready now.

Your package is now registered on packagist, I've also added you as a member to the `laravel-notification-channels`.

If I've done anything you don't like or if there's anything I can do for you, reopen this issue.

Thanks again for your package. I'm pretty sure a lot of people will like it. 👍

**Comment by Omranic** [comment]
Hello @freekmurze 

Thanks for the good work, I just removed `doNotForce` method as it represents the default property value already. Just advice if you've other opinions on this. Other modifications are fine by me 👍

Side note: we’re using git-flow, so all commits goes to `develop` branch instead of `master`, just for future commits.

Would you please add me as a maintainer for this package on @Packagist, thanks again. Hope it will benefit the community.

**Comment by freekmurze** [comment]
@Omranic what is the username I should use on packagist? You GitHub username doesn't seem to exist there.

**Comment by freekmurze** [comment]
Done!
